// Banco de perguntas — TÊNIS (~80). { p, ops[4], r, d }
// Revise as difíceis (d:3) — edite/apague livremente.
window.QUIZ = window.QUIZ || {};
window.QUIZ.tenis = [
  // ---------- nível 1 ----------
  { p: "Quantos torneios do Grand Slam existem por ano?", ops: ["3", "4", "5", "6"], r: 1, d: 1 },
  { p: "Qual Grand Slam é disputado no saibro?", ops: ["Wimbledon", "US Open", "Roland Garros", "Australian Open"], r: 2, d: 1 },
  { p: "Quem é conhecido como o Rei do Saibro?", ops: ["Federer", "Djokovic", "Nadal", "Murray"], r: 2, d: 1 },
  { p: "Qual é o piso de Wimbledon?", ops: ["Saibro", "Grama", "Quadra dura", "Carpete"], r: 1, d: 1 },
  { p: "Quantas vezes Guga venceu Roland Garros?", ops: ["1", "2", "3", "4"], r: 2, d: 1 },
  { p: "Na pontuação do tênis, o que vem depois de 15 e 30?", ops: ["35", "40", "45", "50"], r: 1, d: 1 },
  { p: "Qual a nacionalidade de Roger Federer?", ops: ["Alemão", "Austríaco", "Suíço", "Sueco"], r: 2, d: 1 },
  { p: "Qual a nacionalidade de Novak Djokovic?", ops: ["Croata", "Sérvio", "Búlgaro", "Grego"], r: 1, d: 1 },
  { p: "Em que cidade é disputado o US Open?", ops: ["Los Angeles", "Miami", "Nova York", "Chicago"], r: 2, d: 1 },
  { p: "O que é um 'ace'?", ops: ["Saque que o rival não toca", "Ponto após 20 trocas", "Erro duplo de saque", "Devolução vencedora"], r: 0, d: 1 },
  { p: "Quem forma o 'Big 3' do tênis?", ops: ["Federer, Nadal e Djokovic", "Sampras, Agassi e Becker", "Nadal, Murray e Federer", "Djokovic, Alcaraz e Sinner"], r: 0, d: 1 },
  { p: "No tênis, 'love' significa...", ops: ["zero", "empate", "vantagem", "ponto de ouro"], r: 0, d: 1 },
  { p: "Qual a nacionalidade de Carlos Alcaraz?", ops: ["Argentino", "Espanhol", "Mexicano", "Chileno"], r: 1, d: 1 },
  { p: "Qual a nacionalidade de Jannik Sinner?", ops: ["Austríaco", "Suíço", "Italiano", "Alemão"], r: 2, d: 1 },
  { p: "Roland Garros é disputado em qual cidade?", ops: ["Paris", "Lyon", "Mônaco", "Nice"], r: 0, d: 1 },
  { p: "Nos Grand Slams, os jogos masculinos são em melhor de quantos sets?", ops: ["5", "3", "7", "4"], r: 0, d: 1 },
  { p: "E os jogos femininos, em melhor de quantos sets?", ops: ["3", "5", "2", "4"], r: 0, d: 1 },
  { p: "Quantas tentativas de saque o jogador tem por ponto?", ops: ["2", "1", "3", "Ilimitadas"], r: 0, d: 1 },
  { p: "Quantos quiques a bola pode dar antes da devolução?", ops: ["1", "2", "3", "Nenhum"], r: 0, d: 1 },
  { p: "Venus e Serena Williams são...", ops: ["irmãs", "primas", "mãe e filha", "apenas xarás"], r: 0, d: 1 },
  { p: "Quando o sacador vence sem que o rival toque na bola, é um...", ops: ["Ace", "Winner", "Let", "Lob"], r: 0, d: 1 },
  { p: "A Copa Davis é disputada entre...", ops: ["países", "clubes", "duplas", "universidades"], r: 0, d: 1 },
  { p: "Golpe encobrindo o adversário que subiu à rede:", ops: ["Lob", "Slice", "Smash", "Drop shot"], r: 0, d: 1 },
  { p: "Batida forte de cima para baixo, tipo 'cortada':", ops: ["Smash", "Lob", "Backhand", "Passing shot"], r: 0, d: 1 },

  // ---------- nível 2 ----------
  { p: "O tie-break normal vai até quantos pontos (com 2 de vantagem)?", ops: ["7", "5", "6", "10"], r: 0, d: 2 },
  { p: "Quantos Grand Slams de simples Serena Williams venceu?", ops: ["23", "20", "21", "22"], r: 0, d: 2 },
  { p: "Em que cidade é disputado o Australian Open?", ops: ["Melbourne", "Sydney", "Brisbane", "Perth"], r: 0, d: 2 },
  { p: "Qual cor de vestimenta Wimbledon exige dos jogadores?", ops: ["Branca", "Azul", "Verde", "Livre"], r: 0, d: 2 },
  { p: "O que Guga desenhou no saibro de Roland Garros em 2001?", ops: ["Um coração", "Uma estrela", "As iniciais", "Um sol"], r: 0, d: 2 },
  { p: "Quando o placar chega a 40-40, o ponto se chama...", ops: ["Deuce", "Match point", "Let", "Break"], r: 0, d: 2 },
  { p: "A WTA é a associação do tênis...", ops: ["feminino", "juvenil", "de duplas", "universitário"], r: 0, d: 2 },
  { p: "Qual tenista tem mais Grand Slams masculinos de simples (até 2024)?", ops: ["Djokovic", "Federer", "Nadal", "Sampras"], r: 0, d: 2 },
  { p: "Vencer o game em que o rival saca é conseguir um...", ops: ["Break", "Ace", "Set", "Rally"], r: 0, d: 2 },
  { p: "Quando o saque toca a fita e cai dentro, o árbitro anuncia...", ops: ["Let (repete)", "Falta", "Ponto", "Net out"], r: 0, d: 2 },
  { p: "O que é um 'wild card' (convite)?", ops: ["Vaga dada pela organização", "Um tipo de saque", "Jogador reserva", "Desafio eletrônico"], r: 0, d: 2 },
  { p: "Qual sistema eletrônico confere se a bola quicou dentro?", ops: ["Hawk-Eye (olho de falcão)", "GoalControl", "VAR", "TMO"], r: 0, d: 2 },
  { p: "Qual é a nacionalidade de Andy Murray?", ops: ["Britânico (escocês)", "Irlandês", "Australiano", "Canadense"], r: 0, d: 2 },
  { p: "Qual é a nacionalidade de Daniil Medvedev?", ops: ["Russo", "Ucraniano", "Bielorrusso", "Cazaque"], r: 0, d: 2 },
  { p: "Qual é a nacionalidade de Stefanos Tsitsipas?", ops: ["Grego", "Cipriota", "Turco", "Croata"], r: 0, d: 2 },
  { p: "Qual é a nacionalidade de Iga Swiatek?", ops: ["Polonesa", "Tcheca", "Húngara", "Eslovaca"], r: 0, d: 2 },
  { p: "Qual é a nacionalidade de Naomi Osaka?", ops: ["Japonesa", "Sul-coreana", "Americana", "Filipina"], r: 0, d: 2 },
  { p: "Qual é a nacionalidade de Maria Sharapova?", ops: ["Russa", "Bielorrussa", "Ucraniana", "Letã"], r: 0, d: 2 },
  { p: "Qual é a nacionalidade de Juan Martín del Potro?", ops: ["Argentino", "Uruguaio", "Chileno", "Espanhol"], r: 0, d: 2 },
  { p: "Qual é a nacionalidade de Alexander Zverev?", ops: ["Alemão", "Russo", "Austríaco", "Suíço"], r: 0, d: 2 },
  { p: "De que cidade brasileira é o Guga?", ops: ["Florianópolis", "Porto Alegre", "Curitiba", "São Paulo"], r: 0, d: 2 },
  { p: "Qual dupla de irmãs disputou finais de Wimbledon entre si?", ops: ["Venus e Serena", "Chris e Jeanne", "Steffi e Sabine", "Martina e Manuela"], r: 0, d: 2 },
  { p: "Quem venceu a 'Batalha dos Sexos' contra Bobby Riggs em 1973?", ops: ["Billie Jean King", "Chris Evert", "Margaret Court", "Martina Navratilova"], r: 0, d: 2 },
  { p: "O pó laranja do saibro é feito de...", ops: ["tijolo moído", "argila natural", "areia tingida", "cerâmica vulcânica"], r: 0, d: 2 },
  { p: "Qual é o Grand Slam mais antigo?", ops: ["Wimbledon", "US Open", "Roland Garros", "Australian Open"], r: 0, d: 2 },
  { p: "Qual sobremesa é tradição em Wimbledon?", ops: ["Morangos com creme", "Scones", "Pudim de pão", "Torta de limão"], r: 0, d: 2 },
  { p: "O torneio Roland Garros homenageia um...", ops: ["aviador francês", "tenista francês", "político francês", "escritor francês"], r: 0, d: 2 },
  { p: "Qual torneio brasileiro é o maior da América do Sul?", ops: ["Rio Open", "Brasil Open", "SP Open", "Copa Guga"], r: 0, d: 2 },
  { p: "Qual jovem carioca virou sensação do tênis brasileiro em 2024/25?", ops: ["João Fonseca", "Thiago Wild", "Felipe Meligeni", "Gustavo Heide"], r: 0, d: 2 },
  { p: "Quem foi o primeiro italiano a alcançar o nº 1 do ranking ATP (2024)?", ops: ["Jannik Sinner", "Matteo Berrettini", "Adriano Panatta", "Fabio Fognini"], r: 0, d: 2 },
  { p: "Qual rivalidade marcou os anos 90: Sampras x ...?", ops: ["Agassi", "Becker", "Courier", "Chang"], r: 0, d: 2 },
  { p: "Desde quando as bolas de tênis profissionais são amarelas?", ops: ["Anos 1970", "Anos 1950", "Anos 1990", "Sempre foram"], r: 0, d: 2 },

  // ---------- nível 3 ----------
  { p: "Em que ano Steffi Graf conquistou o Golden Slam?", ops: ["1988", "1984", "1990", "1992"], r: 0, d: 3 },
  { p: "No jargão do tênis, o que é um 'pneu' (bagel)?", ops: ["Set de 6/0", "Jogo sem aces", "Dois erros duplos", "Vitória de virada"], r: 0, d: 3 },
  { p: "Qual brasileira venceu Wimbledon três vezes nos anos 60?", ops: ["Maria Bueno", "Bia Haddad", "Cláudia Monteiro", "Niège Dias"], r: 0, d: 3 },
  { p: "Quantas vezes Federer venceu Wimbledon?", ops: ["8", "6", "7", "9"], r: 0, d: 3 },
  { p: "Quantas vezes Nadal venceu Roland Garros?", ops: ["14", "12", "13", "15"], r: 0, d: 3 },
  { p: "Quem detém o recorde absoluto de Slams de simples no feminino (24)?", ops: ["Margaret Court", "Serena Williams", "Steffi Graf", "Navratilova"], r: 0, d: 3 },
  { p: "Quantos Australian Opens Djokovic venceu até 2024?", ops: ["10", "8", "9", "11"], r: 0, d: 3 },
  { p: "Quem venceu 5 Wimbledons seguidos nos anos 70-80?", ops: ["Björn Borg", "John McEnroe", "Jimmy Connors", "Ivan Lendl"], r: 0, d: 3 },
  { p: "Qual é o bordão eternizado por John McEnroe contra os árbitros?", ops: ["You cannot be serious!", "Out of your mind!", "Are you blind?", "No way, umpire!"], r: 0, d: 3 },
  { p: "Em que ano Guga foi nº 1 do mundo pela primeira vez?", ops: ["2000", "1997", "2001", "1999"], r: 0, d: 3 },
  { p: "Em que ano Guga venceu seu primeiro Roland Garros?", ops: ["1997", "1996", "1998", "2000"], r: 0, d: 3 },
  { p: "Qual brasileira fez semifinal de Roland Garros em 2023?", ops: ["Bia Haddad Maia", "Luisa Stefani", "Laura Pigossi", "Carol Meligeni"], r: 0, d: 3 },
  { p: "Marcelo Melo e Bruno Soares brilharam em qual modalidade?", ops: ["Duplas", "Simples", "Juvenil", "Quadra coberta"], r: 0, d: 3 },
  { p: "Quantos Masters 1000 existem na temporada?", ops: ["9", "7", "8", "10"], r: 0, d: 3 },
  { p: "Qual torneio é apelidado de 'quinto Grand Slam'?", ops: ["Indian Wells", "Miami Open", "Roma", "Madri"], r: 0, d: 3 },
  { p: "O super tie-break do set decisivo vai até quantos pontos?", ops: ["10", "7", "12", "9"], r: 0, d: 3 },
  { p: "Pisar na linha de base durante o saque é...", ops: ["Foot fault", "Let", "Hindrance", "Double fault"], r: 0, d: 3 },
  { p: "Qual a altura aproximada da rede no centro da quadra?", ops: ["91 cm", "1,10 m", "80 cm", "1 m"], r: 0, d: 3 },
  { p: "A Era Aberta (Open Era) do tênis começou em...", ops: ["1968", "1958", "1972", "1980"], r: 0, d: 3 },
  { p: "O estádio principal do US Open leva o nome de...", ops: ["Arthur Ashe", "Billie Jean King", "Jimmy Connors", "Pete Sampras"], r: 0, d: 3 },
  { p: "Qual Grand Slam é apelidado de 'Happy Slam'?", ops: ["Australian Open", "Wimbledon", "US Open", "Roland Garros"], r: 0, d: 3 },
  { p: "Acredita-se que 'love' (zero) venha do francês 'l'oeuf', que significa...", ops: ["ovo", "amor", "vazio", "nada"], r: 0, d: 3 },
  { p: "Quem Alcaraz venceu na final de Wimbledon 2023?", ops: ["Djokovic", "Sinner", "Medvedev", "Rune"], r: 0, d: 3 },
  { p: "Quem se tornou o nº 1 mais jovem da história da ATP em 2022?", ops: ["Alcaraz", "Sinner", "Rune", "Nadal"], r: 0, d: 3 },
  { p: "Djokovic completou o Golden Slam de carreira com o ouro olímpico em...", ops: ["Paris 2024", "Tóquio 2020", "Rio 2016", "Londres 2012"], r: 0, d: 3 },
  { p: "O filme 'King Richard' conta a história do pai de quais tenistas?", ops: ["Venus e Serena", "Steffi e Michael", "Andre e Andrea", "Coco e Sloane"], r: 0, d: 3 },
  { p: "O tênis voltou ao programa olímpico (após 64 anos) em qual edição?", ops: ["Seul 1988", "Los Angeles 1984", "Barcelona 1992", "Moscou 1980"], r: 0, d: 3 },
  { p: "Qual competição por equipes foi criada por Federer em homenagem a uma lenda?", ops: ["Laver Cup", "ATP Cup", "Hopman Cup", "Masters Cup"], r: 0, d: 3 },
  { p: "Qual suíço, além de Federer, venceu 3 Grand Slams?", ops: ["Stan Wawrinka", "Marc Rosset", "Jakob Hlasek", "Heinz Günthardt"], r: 0, d: 3 },
  { p: "Qual argentina foi campeã do US Open em 1990, aos 20 anos?", ops: ["Gabriela Sabatini", "Paola Suárez", "Gisela Dulko", "Clarisa Fernández"], r: 0, d: 3 }
];
