// Bancos de perguntas — { p: pergunta, ops: 4 opções, r: índice da certa, d: dificuldade 1-3 }
// Revisável à mão: basta editar/acrescentar objetos.
window.QUIZ = {

  series: [
    { p: "Em Friends, qual é o nome do café onde a turma se encontra?", ops: ["Central Perk", "Perk Place", "Coffee Central", "Java Joe's"], r: 0, d: 1 },
    { p: "Em Breaking Bad, qual era a profissão original de Walter White?", ops: ["Farmacêutico", "Professor de química", "Engenheiro químico", "Médico"], r: 1, d: 1 },
    { p: "Em Stranger Things, qual RPG os meninos jogam no porão?", ops: ["War", "Magic", "Dungeons & Dragons", "GURPS"], r: 2, d: 1 },
    { p: "Qual é o lema da casa Stark em Game of Thrones?", ops: ["Fogo e Sangue", "Ouvi Rugir", "Nós Não Semeamos", "O Inverno Está Chegando"], r: 3, d: 1 },
    { p: "Em The Office (EUA), qual o nome da empresa de papel?", ops: ["Dunder Mifflin", "Sabre Paper", "Michael Scott Co.", "Scranton Paper"], r: 0, d: 1 },
    { p: "Em Grey's Anatomy, qual o nome atual do hospital?", ops: ["Seattle Grace", "Mercy West", "Grey Sloan Memorial", "Sacred Heart"], r: 2, d: 2 },
    { p: "Em La Casa de Papel, os assaltantes usam codinomes de quê?", ops: ["Planetas", "Cidades", "Pintores", "Rios"], r: 1, d: 1 },
    { p: "Na série alemã Dark, como se chama a cidadezinha da trama?", ops: ["Winden", "Warten", "Wolfsburg", "Werder"], r: 0, d: 2 },
    { p: "The Crown retrata o reinado de qual monarca?", ops: ["Vitória", "George VI", "Elizabeth II", "Charles III"], r: 2, d: 1 },
    { p: "Em Seinfeld, quem é o vizinho que entra sem bater?", ops: ["George", "Newman", "Kramer", "Puddy"], r: 2, d: 2 },
    { p: "Em Lost, qual o número do voo que cai na ilha?", ops: ["Oceanic 815", "Oceanic 714", "Ajira 316", "Pacific 815"], r: 0, d: 2 },
    { p: "Better Call Saul é spin-off de qual série?", ops: ["The Wire", "Breaking Bad", "Ozark", "Fargo"], r: 1, d: 1 },
    { p: "Em The Big Bang Theory, em que porta Sheldon bate três vezes chamando o nome?", ops: ["Na do Leonard", "Na da Penny", "Na do Howard", "Na da Amy"], r: 1, d: 1 },
    { p: "Em Downton Abbey, qual é o sobrenome da família aristocrata?", ops: ["Bridgerton", "Grantham", "Crawley", "Carson"], r: 2, d: 2 },
    { p: "A minissérie Chernobyl retrata um acidente ocorrido em que ano?", ops: ["1979", "1986", "1991", "1983"], r: 1, d: 2 },
    { p: "Em Succession, qual é o nome do conglomerado da família Roy?", ops: ["Waystar Royco", "RoyCorp", "Vaulter Media", "ATN Global"], r: 0, d: 2 },
    { p: "Em Peaky Blinders, em qual cidade inglesa vive a família Shelby?", ops: ["Manchester", "Liverpool", "Londres", "Birmingham"], r: 3, d: 2 },
    { p: "Qual é a especialidade do Dr. House?", ops: ["Diagnóstico", "Cirurgia", "Cardiologia", "Neurologia"], r: 0, d: 1 },
    { p: "Quantos amigos formam o grupo principal de Friends?", ops: ["4", "5", "6", "7"], r: 2, d: 1 },
    { p: "Em The Walking Dead, qual o nome do xerife protagonista?", ops: ["Daryl Dixon", "Rick Grimes", "Shane Walsh", "Glenn Rhee"], r: 1, d: 1 },
    { p: "Qual é o tema central de Black Mirror?", ops: ["Crimes reais", "Tecnologia e sociedade", "Política americana", "Viagens no tempo"], r: 1, d: 1 },
    { p: "A 1ª temporada de Narcos foca em qual figura?", ops: ["El Chapo", "Cali Cartel", "Pablo Escobar", "Griselda"], r: 2, d: 1 },
    { p: "Em The Handmaid's Tale, como se chama a república totalitária?", ops: ["Gilead", "Panem", "Oceania", "Eden"], r: 0, d: 2 },
    { p: "Quem interpreta Sherlock na série da BBC?", ops: ["Martin Freeman", "Tom Hiddleston", "Benedict Cumberbatch", "Eddie Redmayne"], r: 2, d: 2 },
    { p: "Mad Men se passa no mundo de qual profissão?", ops: ["Jornalismo", "Publicidade", "Moda", "Cinema"], r: 1, d: 2 },
    { p: "Quem é o protagonista das primeiras temporadas de Vikings?", ops: ["Bjorn", "Rollo", "Floki", "Ragnar Lothbrok"], r: 3, d: 2 },
    { p: "Quem cria e estrela Fleabag?", ops: ["Phoebe Waller-Bridge", "Michaela Coel", "Sharon Horgan", "Aisling Bea"], r: 0, d: 3 },
    { p: "The Wire se passa em qual cidade americana?", ops: ["Detroit", "Chicago", "Baltimore", "Filadélfia"], r: 2, d: 3 },
    { p: "Qual pergunta move a trama de Twin Peaks?", ops: ["Quem matou Laura Palmer?", "Onde está Audrey?", "Quem é Bob?", "O que há na floresta?"], r: 0, d: 3 },
    { p: "Em The Sopranos, Tony comanda uma família mafiosa de qual estado?", ops: ["Nova York", "Nova Jersey", "Connecticut", "Pensilvânia"], r: 1, d: 2 }
  ],

  palmeiras: [
    { p: "Em que ano o Palmeiras foi fundado?", ops: ["1910", "1912", "1914", "1916"], r: 2, d: 1 },
    { p: "Qual foi o nome de fundação do Palmeiras?", ops: ["Palestra Itália", "Società Palmeiras", "Itália FC", "Verdão SC"], r: 0, d: 1 },
    { p: "Qual é o estádio atual do Palmeiras?", ops: ["Pacaembu", "Allianz Parque", "Arena Palestra", "Morumbi"], r: 1, d: 1 },
    { p: "Qual animal virou símbolo da torcida palmeirense nos anos 80?", ops: ["Leão", "Periquito", "Porco", "Touro"], r: 2, d: 2 },
    { p: "Quem era o técnico do Palmeiras na Libertadores de 1999?", ops: ["Luxemburgo", "Felipão", "Emerson Leão", "Telê Santana"], r: 1, d: 2 },
    { p: "Quem foi o técnico das Libertadores de 2020 e 2021?", ops: ["Cuca", "Renato Gaúcho", "Abel Ferreira", "Jorge Jesus"], r: 2, d: 1 },
    { p: "Qual clássico é conhecido como Derby Paulista?", ops: ["Palmeiras x Santos", "Palmeiras x Corinthians", "Palmeiras x São Paulo", "Corinthians x São Paulo"], r: 1, d: 1 },
    { p: "Quais são as cores do Palmeiras?", ops: ["Verde e branco", "Verde e amarelo", "Verde e preto", "Verde e vermelho"], r: 0, d: 1 },
    { p: "Como ficou conhecido o grande time palmeirense dos anos 60?", ops: ["A Máquina", "O Esquadrão", "A Academia", "O Expresso"], r: 2, d: 2 },
    { p: "Qual era o apelido de Ademir da Guia?", ops: ["O Divino", "O Rei", "O Maestro", "O Príncipe"], r: 0, d: 2 },
    { p: "Para qual clube o Endrick foi vendido?", ops: ["Barcelona", "Real Madrid", "PSG", "Manchester City"], r: 1, d: 1 },
    { p: "Quem era o goleiro campeão da Libertadores de 2020?", ops: ["Fernando Prass", "Jailson", "Weverton", "Marcos"], r: 2, d: 1 },
    { p: "Quem era o goleiro ídolo campeão da Libertadores de 1999?", ops: ["Marcos", "Velloso", "Sérgio", "Zetti"], r: 0, d: 1 },
    { p: "Por que o Palestra Itália mudou de nome em 1942?", ops: ["Falência da diretoria", "Fusão com outro clube", "Proibição de nomes do Eixo na 2ª Guerra", "Exigência da FIFA"], r: 2, d: 2 },
    { p: "Qual torneio intercontinental de 1951 o Palmeiras venceu?", ops: ["Copa Rio", "Pequena Taça do Mundo", "Torneio de Paris", "Copa Ouro"], r: 0, d: 3 },
    { p: "No hino: 'Quando surge o alviverde imponente, no gramado em que...'", ops: ["a glória o aguarda", "a luta o aguarda", "o povo o aguarda", "a taça o aguarda"], r: 1, d: 3 },
    { p: "Como se chamava o antigo estádio no terreno do Allianz Parque?", ops: ["Parque São Jorge", "Palestra Itália (Parque Antártica)", "Estádio das Palmeiras", "Canindé"], r: 1, d: 1 },
    { p: "Quem é a presidente do Palmeiras ligada à Crefisa?", ops: ["Leila Pereira", "Marlene Matheus", "Patrícia Amorim", "Sônia Guedes"], r: 0, d: 1 },
    { p: "Contra quem foi a final da Libertadores de 2021?", ops: ["River Plate", "Boca Juniors", "Flamengo", "Athletico-PR"], r: 2, d: 2 },
    { p: "Contra quem foi a final da Libertadores de 2020?", ops: ["Santos", "Grêmio", "São Paulo", "Defensa y Justicia"], r: 0, d: 2 },
    { p: "Contra quem o Palmeiras venceu a final da Libertadores de 1999?", ops: ["River Plate", "Deportivo Cali", "Colo-Colo", "Cerro Porteño"], r: 1, d: 3 },
    { p: "Qual meia camisa 10 foi o craque do título da Libertadores de 1999?", ops: ["Rivaldo", "Djalminha", "Alex", "Zinho"], r: 2, d: 3 },
    { p: "Qual é o apelido mais famoso do Palmeiras?", ops: ["Tricolor", "Verdão", "Peixe", "Timão"], r: 1, d: 1 },
    { p: "Até 2023, quantos Campeonatos Brasileiros (incluindo a Taça Brasil) o Palmeiras somava?", ops: ["9", "10", "11", "12"], r: 3, d: 3 }
  ],

  tenis: [
    { p: "Quantos torneios do Grand Slam existem por ano?", ops: ["3", "4", "5", "6"], r: 1, d: 1 },
    { p: "Qual Grand Slam é disputado no saibro?", ops: ["Wimbledon", "US Open", "Roland Garros", "Australian Open"], r: 2, d: 1 },
    { p: "Quem é conhecido como o Rei do Saibro?", ops: ["Federer", "Djokovic", "Nadal", "Murray"], r: 2, d: 1 },
    { p: "Qual é o piso de Wimbledon?", ops: ["Saibro", "Grama", "Quadra dura", "Carpete"], r: 1, d: 1 },
    { p: "Quantas vezes Guga venceu Roland Garros?", ops: ["1", "2", "3", "4"], r: 2, d: 1 },
    { p: "Na pontuação do tênis, o que vem depois de 15 e 30?", ops: ["35", "40", "45", "50"], r: 1, d: 1 },
    { p: "O tie-break normal vai até quantos pontos (com 2 de vantagem)?", ops: ["5", "6", "7", "10"], r: 2, d: 2 },
    { p: "Qual a nacionalidade de Roger Federer?", ops: ["Alemão", "Austríaco", "Suíço", "Sueco"], r: 2, d: 1 },
    { p: "Qual a nacionalidade de Novak Djokovic?", ops: ["Croata", "Sérvio", "Búlgaro", "Grego"], r: 1, d: 1 },
    { p: "Quantos Grand Slams de simples Serena Williams venceu?", ops: ["20", "21", "22", "23"], r: 3, d: 2 },
    { p: "Em que cidade é disputado o Australian Open?", ops: ["Sydney", "Melbourne", "Brisbane", "Perth"], r: 1, d: 2 },
    { p: "Em que cidade é disputado o US Open?", ops: ["Los Angeles", "Miami", "Nova York", "Chicago"], r: 2, d: 1 },
    { p: "O que é um 'ace'?", ops: ["Saque que o rival não toca", "Ponto após 20 trocas", "Erro duplo de saque", "Devolução vencedora"], r: 0, d: 1 },
    { p: "Em que ano Steffi Graf conquistou o Golden Slam?", ops: ["1984", "1988", "1990", "1992"], r: 1, d: 3 },
    { p: "Qual cor de vestimenta Wimbledon exige dos jogadores?", ops: ["Azul", "Branca", "Verde", "Livre"], r: 1, d: 2 },
    { p: "O que Guga desenhou no saibro de Roland Garros em 2001?", ops: ["Uma estrela", "Um coração", "As iniciais", "Um sol"], r: 1, d: 2 },
    { p: "No jargão do tênis, o que é um 'pneu' (bagel)?", ops: ["Set de 6/0", "Jogo sem aces", "Dois erros duplos", "Vitória de virada"], r: 0, d: 3 },
    { p: "Qual brasileira venceu Wimbledon três vezes nos anos 60?", ops: ["Maria Bueno", "Bia Haddad", "Cláudia Monteiro", "Niège Dias"], r: 0, d: 3 },
    { p: "Quem forma o 'Big 3' do tênis?", ops: ["Federer, Nadal e Djokovic", "Sampras, Agassi e Becker", "Nadal, Murray e Federer", "Djokovic, Alcaraz e Sinner"], r: 0, d: 1 },
    { p: "Quando o placar chega a 40-40, o ponto se chama...", ops: ["Match point", "Deuce", "Let", "Break"], r: 1, d: 2 }
  ],

  italia: [
    { p: "Qual é a capital da Itália?", ops: ["Milão", "Roma", "Florença", "Nápoles"], r: 1, d: 1 },
    { p: "Em qual fonte de Roma se joga moeda para voltar à cidade?", ops: ["Fontana di Trevi", "Fontana del Moro", "Quattro Fiumi", "Barcaccia"], r: 0, d: 1 },
    { p: "O Coliseu era palco principalmente de quê?", ops: ["Corridas de biga", "Peças de teatro", "Lutas de gladiadores", "Julgamentos"], r: 2, d: 1 },
    { p: "O Vaticano é famoso por ser...", ops: ["o menor país do mundo", "uma província romana", "um bairro de Roma", "uma ilha"], r: 0, d: 1 },
    { p: "Em qual cidade fica a famosa torre inclinada?", ops: ["Siena", "Bolonha", "Pisa", "Verona"], r: 2, d: 1 },
    { p: "Qual cidade italiana é conhecida pelos canais e gôndolas?", ops: ["Gênova", "Veneza", "Trieste", "Bari"], r: 1, d: 1 },
    { p: "A Puglia fica em qual parte da Itália?", ops: ["No norte", "No centro", "No 'salto da bota', ao sul", "Na costa oeste"], r: 2, d: 2 },
    { p: "Onde ficam os trulli, as casinhas cônicas da Puglia?", ops: ["Alberobello", "Ostuni", "Lecce", "Matera"], r: 0, d: 2 },
    { p: "A Sardenha é...", ops: ["uma península", "uma ilha", "uma região alpina", "uma cidade"], r: 1, d: 1 },
    { p: "Qual costa da Sardenha é famosa pelo mar verde-esmeralda?", ops: ["Costa Amalfitana", "Costa Esmeralda", "Cinque Terre", "Riviera Ligure"], r: 1, d: 2 },
    { p: "Qual massa em formato de 'orelhinha' é típica da Puglia?", ops: ["Farfalle", "Trofie", "Orecchiette", "Cavatelli"], r: 2, d: 2 },
    { p: "As cores da pizza margherita homenageiam...", ops: ["a rainha da Áustria", "a bandeira italiana", "o Vaticano", "a cidade de Nápoles"], r: 1, d: 1 },
    { p: "Qual vulcão fica perto de Nápoles?", ops: ["Etna", "Stromboli", "Vesúvio", "Vulcano"], r: 2, d: 1 },
    { p: "Qual cidade romana foi soterrada pelo Vesúvio em 79 d.C.?", ops: ["Óstia", "Pompeia", "Cápua", "Ravena"], r: 1, d: 1 },
    { p: "Em qual cidade está o Davi de Michelangelo?", ops: ["Roma", "Milão", "Florença", "Turim"], r: 2, d: 2 },
    { p: "Quem pintou o teto da Capela Sistina?", ops: ["Rafael", "Michelangelo", "Da Vinci", "Caravaggio"], r: 1, d: 1 },
    { p: "O que significa 'dolce far niente'?", ops: ["Doce da tarde", "O doce prazer de não fazer nada", "Comer devagar", "Vida doce e curta"], r: 1, d: 2 },
    { p: "Para o italiano tradicional, pedir cappuccino depois do almoço é...", ops: ["obrigatório", "coisa de turista", "sinal de elegância", "proibido por lei"], r: 1, d: 2 },
    { p: "Segundo a lenda, Roma foi fundada por...", ops: ["Júlio César", "Rômulo e Remo", "Enéas", "Augusto"], r: 1, d: 1 },
    { p: "Qual rio corta a cidade de Roma?", ops: ["Arno", "Pó", "Tibre", "Ádige"], r: 2, d: 2 },
    { p: "O Panteão de Roma é famoso por qual detalhe da cúpula?", ops: ["O óculo aberto no topo", "Os vitrais", "O mosaico dourado", "As gárgulas"], r: 0, d: 3 },
    { p: "Roma fica em qual região da Itália?", ops: ["Toscana", "Lácio", "Úmbria", "Campânia"], r: 1, d: 3 },
    { p: "Qual aperitivo italiano leva Aperol e prosecco?", ops: ["Negroni", "Bellini", "Spritz", "Campari tônica"], r: 2, d: 1 },
    { p: "Em qual cidade fica a sede da Ferrari?", ops: ["Módena", "Maranello", "Bolonha", "Monza"], r: 1, d: 3 },
    { p: "A bandeira da Itália é verde, branca e...", ops: ["azul", "amarela", "vermelha", "preta"], r: 2, d: 1 }
  ]
};
