// Banco de perguntas — SÉRIES (~200). { p, ops[4], r: índice da certa, d: 1-3 }
// Revise as difíceis (d:3) — edite/apague livremente.
window.QUIZ = window.QUIZ || {};
window.QUIZ.series = [
  // ---------- nível 1 ----------
  { p: "Em Friends, qual é o nome do café onde a turma se encontra?", ops: ["Central Perk", "Perk Place", "Coffee Central", "Java Joe's"], r: 0, d: 1 },
  { p: "Em Breaking Bad, qual era a profissão original de Walter White?", ops: ["Farmacêutico", "Professor de química", "Engenheiro químico", "Médico"], r: 1, d: 1 },
  { p: "Em Stranger Things, qual RPG os meninos jogam no porão?", ops: ["War", "Magic", "Dungeons & Dragons", "GURPS"], r: 2, d: 1 },
  { p: "Qual é o lema da casa Stark em Game of Thrones?", ops: ["Fogo e Sangue", "Ouvi Rugir", "Nós Não Semeamos", "O Inverno Está Chegando"], r: 3, d: 1 },
  { p: "Em The Office (EUA), qual o nome da empresa de papel?", ops: ["Dunder Mifflin", "Sabre Paper", "Michael Scott Co.", "Scranton Paper"], r: 0, d: 1 },
  { p: "Qual apelido Walter White usa no mundo do crime?", ops: ["Heisenberg", "Eisenhower", "Fring", "Capitão Cook"], r: 0, d: 1 },
  { p: "Em Game of Thrones, quantos dragões Daenerys tem?", ops: ["1", "2", "3", "4"], r: 2, d: 1 },
  { p: "Em How I Met Your Mother, Ted narra a história para quem?", ops: ["O terapeuta", "Os filhos", "O Barney", "Um diário"], r: 1, d: 1 },
  { p: "Em La Casa de Papel, quem arquiteta o assalto?", ops: ["Berlim", "O Professor", "Palermo", "Tóquio"], r: 1, d: 1 },
  { p: "Round 6 (Squid Game) é uma série de qual país?", ops: ["Japão", "China", "Coreia do Sul", "Tailândia"], r: 2, d: 1 },
  { p: "Em Ted Lasso, qual esporte o técnico americano vai treinar na Inglaterra?", ops: ["Rúgbi", "Críquete", "Futebol", "Basquete"], r: 2, d: 1 },
  { p: "Qual é a especialidade do Dr. House?", ops: ["Diagnóstico", "Cirurgia", "Cardiologia", "Neurologia"], r: 0, d: 1 },
  { p: "Quantos amigos formam o grupo principal de Friends?", ops: ["4", "5", "6", "7"], r: 2, d: 1 },
  { p: "Em The Walking Dead, qual o nome do xerife protagonista?", ops: ["Daryl Dixon", "Rick Grimes", "Shane Walsh", "Glenn Rhee"], r: 1, d: 1 },
  { p: "Qual é o tema central de Black Mirror?", ops: ["Crimes reais", "Tecnologia e sociedade", "Política americana", "Viagens no tempo"], r: 1, d: 1 },
  { p: "A 1ª temporada de Narcos foca em qual figura?", ops: ["El Chapo", "Cartel de Cali", "Pablo Escobar", "Griselda"], r: 2, d: 1 },
  { p: "Better Call Saul é spin-off de qual série?", ops: ["The Wire", "Breaking Bad", "Ozark", "Fargo"], r: 1, d: 1 },
  { p: "The Crown retrata o reinado de qual monarca?", ops: ["Vitória", "George VI", "Elizabeth II", "Charles III"], r: 2, d: 1 },
  { p: "Em The Big Bang Theory, em que porta Sheldon bate três vezes chamando o nome?", ops: ["Na do Leonard", "Na da Penny", "Na do Howard", "Na da Amy"], r: 1, d: 1 },
  { p: "Em Wandinha, qual é o nome da mão que a acompanha?", ops: ["Mãozinha (Coisa)", "Dedão", "Garra", "Luva"], r: 0, d: 1 },
  { p: "Wandinha pertence a qual família?", ops: ["Munster", "Addams", "Locke", "Belcher"], r: 1, d: 1 },
  { p: "Em The Witcher, qual o nome do protagonista caçador de monstros?", ops: ["Geralt de Rívia", "Jaskier", "Vesemir", "Emhyr"], r: 0, d: 1 },
  { p: "Na Casa de Papel, qual pintor estampa as máscaras?", ops: ["Picasso", "Goya", "Dalí", "Miró"], r: 2, d: 1 },
  { p: "Qual música virou hino da resistência em La Casa de Papel?", ops: ["Bella Ciao", "Volare", "Gloria", "Sarà perché ti amo"], r: 0, d: 1 },
  { p: "Em The Queen's Gambit, qual jogo Beth Harmon domina?", ops: ["Pôquer", "Xadrez", "Bridge", "Gamão"], r: 1, d: 1 },
  { p: "Em The Last of Us, quem são os protagonistas?", ops: ["Joel e Ellie", "Rick e Carl", "Max e Chloe", "Kratos e Atreus"], r: 0, d: 1 },
  { p: "Em Peaky Blinders, quem lidera a família Shelby?", ops: ["Arthur", "Michael", "Thomas", "Finn"], r: 2, d: 1 },
  { p: "Em Sex and the City, qual é a profissão de Carrie Bradshaw?", ops: ["Colunista", "Advogada", "Estilista", "Galerista"], r: 0, d: 1 },
  { p: "Em Supernatural, quais são os irmãos caçadores?", ops: ["Sam e Dean", "Damon e Stefan", "Scott e Stiles", "Lucas e Nathan"], r: 0, d: 1 },
  { p: "Nos Simpsons, em que cidade a família mora?", ops: ["Springfield", "Shelbyville", "Quahog", "South Park"], r: 0, d: 1 },
  { p: "Nos Simpsons, onde Homer trabalha?", ops: ["Usina nuclear", "Fábrica de donuts", "Correios", "Taverna do Moe"], r: 0, d: 1 },
  { p: "Qual é o bordão do Homer Simpson?", ops: ["D'oh!", "Ai caramba!", "Yabba dabba doo!", "Cowabunga!"], r: 0, d: 1 },
  { p: "Em Friends, qual é a profissão da Monica?", ops: ["Chef de cozinha", "Massagista", "Atriz", "Publicitária"], r: 0, d: 1 },
  { p: "Qual é o bordão do Joey em Friends?", ops: ["How you doin'?", "Smelly cat!", "We were on a break!", "Pivot!"], r: 0, d: 1 },
  { p: "Qual música a Phoebe canta no Central Perk?", ops: ["Smelly Cat", "Wonderwall", "Creep", "Angry Dog"], r: 0, d: 1 },
  { p: "Em Gossip Girl, como a narradora assina as mensagens?", ops: ["XOXO", "Beijos, GG", "Até nunca", "Com amor, NY"], r: 0, d: 1 },
  { p: "Em Cobra Kai, a história continua qual filme clássico?", ops: ["Karatê Kid", "Rocky", "Curtindo a Vida Adoidado", "De Volta para o Futuro"], r: 0, d: 1 },
  { p: "Em The Mandalorian, qual o nome do 'baby Yoda'?", ops: ["Grogu", "Yaddle", "Kuiil", "Womp"], r: 0, d: 1 },
  { p: "Em Mad Men, qual é o nome do publicitário protagonista?", ops: ["Don Draper", "Roger Sterling", "Pete Campbell", "Ken Cosgrove"], r: 0, d: 1 },
  { p: "Em Prison Break, o que Michael tatua no corpo?", ops: ["A planta da prisão", "O rosto do irmão", "Um mapa do tesouro", "Códigos bancários"], r: 0, d: 1 },
  { p: "A série 24 Horas é famosa por se passar...", ops: ["em tempo real", "ao contrário", "em preto e branco", "sem diálogos"], r: 0, d: 1 },
  { p: "Em Grey's Anatomy, quem é a protagonista que dá nome à série?", ops: ["Meredith Grey", "Cristina Yang", "Izzie Stevens", "Lexie Grey"], r: 0, d: 1 },
  { p: "Em Grey's Anatomy, qual o apelido do Dr. Derek Shepherd?", ops: ["McDreamy", "McSteamy", "McDoctor", "McPerfect"], r: 0, d: 1 },
  { p: "Em The Good Doctor, qual condição tem o Dr. Shaun Murphy?", ops: ["Autismo", "Cegueira", "Amnésia", "Narcolepsia"], r: 0, d: 1 },
  { p: "Em Stranger Things, qual é o poder da Eleven?", ops: ["Telecinese", "Invisibilidade", "Voar", "Ler mentes à distância"], r: 0, d: 1 },
  { p: "Em Stranger Things, em que cidade tudo acontece?", ops: ["Hawkins", "Derry", "Castle Rock", "Riverdale"], r: 0, d: 1 },
  { p: "Em Game of Thrones, como se chama o continente principal?", ops: ["Westeros", "Essos", "Valíria", "Sothoryos"], r: 0, d: 1 },
  { p: "Qual é o trono disputado em Game of Thrones?", ops: ["Trono de Ferro", "Trono de Ouro", "Trono de Gelo", "Trono de Sal"], r: 0, d: 1 },
  { p: "Jon Snow serve em qual ordem no início de Game of Thrones?", ops: ["Patrulha da Noite", "Guarda Real", "Mãos do Rei", "Imaculados"], r: 0, d: 1 },
  { p: "Em Breaking Bad, qual a cor da metanfetamina de Walter?", ops: ["Azul", "Verde", "Rosa", "Branca"], r: 0, d: 1 },
  { p: "Em Breaking Bad, quem é o ex-aluno que vira sócio de Walter?", ops: ["Jesse Pinkman", "Badger", "Skinny Pete", "Todd"], r: 0, d: 1 },
  { p: "Em The Handmaid's Tale, qual a cor das vestes das aias?", ops: ["Vermelha", "Azul", "Verde", "Cinza"], r: 0, d: 1 },
  { p: "Em Sherlock (BBC), qual é o endereço do detetive?", ops: ["221B Baker Street", "10 Downing Street", "4 Privet Drive", "742 Evergreen Terrace"], r: 0, d: 1 },
  { p: "Em Round 6, qual é a primeira prova?", ops: ["Batatinha frita 1, 2, 3", "Cabo de guerra", "Bolinhas de gude", "Ponte de vidro"], r: 0, d: 1 },
  { p: "Em Emily in Paris, para qual cidade Emily se muda?", ops: ["Paris", "Roma", "Londres", "Milão"], r: 0, d: 1 },

  // ---------- nível 2 ----------
  { p: "Em Grey's Anatomy, qual o nome atual do hospital?", ops: ["Seattle Grace", "Mercy West", "Grey Sloan Memorial", "Sacred Heart"], r: 2, d: 2 },
  { p: "Em La Casa de Papel, os assaltantes usam codinomes de quê?", ops: ["Planetas", "Cidades", "Pintores", "Rios"], r: 1, d: 2 },
  { p: "Na série alemã Dark, como se chama a cidadezinha da trama?", ops: ["Winden", "Warten", "Wolfsburg", "Werder"], r: 0, d: 2 },
  { p: "Em Seinfeld, quem é o vizinho que entra sem bater?", ops: ["George", "Newman", "Kramer", "Puddy"], r: 2, d: 2 },
  { p: "Em Lost, qual o número do voo que cai na ilha?", ops: ["Oceanic 815", "Oceanic 714", "Ajira 316", "Pacific 815"], r: 0, d: 2 },
  { p: "Em Downton Abbey, qual é o sobrenome da família aristocrata?", ops: ["Bridgerton", "Grantham", "Crawley", "Carson"], r: 2, d: 2 },
  { p: "A minissérie Chernobyl retrata um acidente ocorrido em que ano?", ops: ["1979", "1986", "1991", "1983"], r: 1, d: 2 },
  { p: "Em Succession, qual é o nome do conglomerado da família Roy?", ops: ["Waystar Royco", "RoyCorp", "Vaulter Media", "ATN Global"], r: 0, d: 2 },
  { p: "Em Peaky Blinders, em qual cidade inglesa vive a família Shelby?", ops: ["Manchester", "Liverpool", "Londres", "Birmingham"], r: 3, d: 2 },
  { p: "Em The Handmaid's Tale, como se chama a república totalitária?", ops: ["Gilead", "Panem", "Oceania", "Eden"], r: 0, d: 2 },
  { p: "Quem interpreta Sherlock na série da BBC?", ops: ["Martin Freeman", "Tom Hiddleston", "Benedict Cumberbatch", "Eddie Redmayne"], r: 2, d: 2 },
  { p: "Mad Men se passa no mundo de qual profissão?", ops: ["Jornalismo", "Publicidade", "Moda", "Cinema"], r: 1, d: 2 },
  { p: "Quem é o protagonista das primeiras temporadas de Vikings?", ops: ["Bjorn", "Rollo", "Floki", "Ragnar Lothbrok"], r: 3, d: 2 },
  { p: "Em The Sopranos, Tony comanda uma família mafiosa de qual estado?", ops: ["Nova York", "Nova Jersey", "Connecticut", "Pensilvânia"], r: 1, d: 2 },
  { p: "The Bear se passa na cozinha de um restaurante de qual cidade?", ops: ["Nova York", "Chicago", "Filadélfia", "Boston"], r: 1, d: 2 },
  { p: "Em The Last of Us, o colapso do mundo é causado por...", ops: ["um vírus", "um fungo", "radiação", "uma bactéria"], r: 1, d: 2 },
  { p: "Em Wandinha, qual é o nome da escola?", ops: ["Nunca Mais", "Hogwarts", "Ravenswood", "Baskerville"], r: 0, d: 2 },
  { p: "Em Friends: 'We were on a...'", ops: ["pause", "break", "stop", "timeout"], r: 1, d: 2 },
  { p: "Em The Office, Jim prende o grampeador do Dwight dentro de...", ops: ["gelatina", "concreto", "um cofre", "uma melancia"], r: 0, d: 2 },
  { p: "Gilmore Girls se passa na cidadezinha de...", ops: ["Stars Hollow", "Bluebell", "Capeside", "Tree Hill"], r: 0, d: 2 },
  { p: "Em Bridgerton, quem assina as crônicas de fofoca?", ops: ["Lady Danbury", "Lady Whistledown", "Rainha Charlotte", "Penelope Bridgerton"], r: 1, d: 2 },
  { p: "Em Emily in Paris, Emily trabalha com...", ops: ["moda", "gastronomia", "marketing", "jornalismo"], r: 2, d: 2 },
  { p: "Em Grey's Anatomy, quem diz a Meredith: 'você é minha pessoa'?", ops: ["Izzie", "Cristina", "Alex", "Bailey"], r: 1, d: 2 },
  { p: "Cada temporada de The White Lotus se passa em...", ops: ["um resort diferente", "um cruzeiro", "uma mansão", "uma ilha deserta"], r: 0, d: 2 },
  { p: "Em Severance, o procedimento da Lumon separa...", ops: ["memórias do trabalho e da vida", "corpo e alma", "sonho e realidade", "passado e futuro"], r: 0, d: 2 },
  { p: "Em Friends, qual é a profissão do Ross?", ops: ["Paleontólogo", "Arqueólogo", "Físico", "Geólogo"], r: 0, d: 2 },
  { p: "Qual é o nome do macaco do Ross em Friends?", ops: ["Marcel", "Momo", "Abu", "George"], r: 0, d: 2 },
  { p: "Em Friends, qual é o primeiro emprego da Rachel?", ops: ["Garçonete no Central Perk", "Vendedora na Ralph Lauren", "Compradora na Bloomingdale's", "Recepcionista"], r: 0, d: 2 },
  { p: "Em Friends, por quem Gunther é apaixonado?", ops: ["Rachel", "Monica", "Phoebe", "Janice"], r: 0, d: 2 },
  { p: "Em The Big Bang Theory, onde a Penny trabalha no início?", ops: ["Cheesecake Factory", "Starbucks", "McDonald's", "Numa livraria"], r: 0, d: 2 },
  { p: "Em The Big Bang Theory, qual problema o Raj tinha com mulheres?", ops: ["Não conseguia falar com elas", "Fugia delas", "Só falava em hindi", "Desmaiava"], r: 0, d: 2 },
  { p: "Em The Big Bang Theory, quem NÃO tem doutorado?", ops: ["Howard", "Sheldon", "Leonard", "Raj"], r: 0, d: 2 },
  { p: "Qual é a área da Amy em The Big Bang Theory?", ops: ["Neurobiologia", "Astrofísica", "Química", "Matemática"], r: 0, d: 2 },
  { p: "Em The Office, em que cidade fica a filial de Michael Scott?", ops: ["Scranton", "Stamford", "Utica", "Nashua"], r: 0, d: 2 },
  { p: "Quem interpreta Michael Scott em The Office?", ops: ["Steve Carell", "Ed Helms", "John Krasinski", "Rainn Wilson"], r: 0, d: 2 },
  { p: "Em The Office, o que Dwight cultiva em sua fazenda?", ops: ["Beterrabas", "Batatas", "Abóboras", "Milho"], r: 0, d: 2 },
  { p: "Em The Office, qual era o primeiro emprego da Pam na empresa?", ops: ["Recepcionista", "Vendedora", "Contadora", "RH"], r: 0, d: 2 },
  { p: "Em Seinfeld, qual é o sobrenome do George?", ops: ["Costanza", "Kramer", "Benes", "Newman"], r: 0, d: 2 },
  { p: "Qual é o bordão do 'Soup Nazi' em Seinfeld?", ops: ["No soup for you!", "Soup is over!", "Get out, no soup!", "Next!"], r: 0, d: 2 },
  { p: "Em Modern Family, qual é a nacionalidade da Gloria?", ops: ["Colombiana", "Mexicana", "Venezuelana", "Brasileira"], r: 0, d: 2 },
  { p: "Em Modern Family, qual é o sobrenome de Phil e Claire?", ops: ["Dunphy", "Pritchett", "Tucker", "Delgado"], r: 0, d: 2 },
  { p: "Em Brooklyn Nine-Nine, qual é o nome do capitão?", ops: ["Raymond Holt", "Terry Jeffords", "Jake Peralta", "Michael Hitchcock"], r: 0, d: 2 },
  { p: "Em Schitt's Creek, por que a família Rose vai morar na cidadezinha?", ops: ["Perderam a fortuna", "Herdaram uma fazenda", "Fugiram da máfia", "Ganharam na loteria"], r: 0, d: 2 },
  { p: "Em The Good Place, por que os palavrões viram 'fork' e 'shirt'?", ops: ["O lugar censura automaticamente", "É regra da Eleanor", "É uma aposta", "Erro de tradução"], r: 0, d: 2 },
  { p: "Em How I Met Your Mother, qual é o bar da turma?", ops: ["MacLaren's", "Paddy's", "Cheers", "Moe's"], r: 0, d: 2 },
  { p: "Qual é a profissão do Ted em How I Met Your Mother?", ops: ["Arquiteto", "Advogado", "Professor de história", "Publicitário"], r: 0, d: 2 },
  { p: "Em Stranger Things, qual é a comida favorita da Eleven?", ops: ["Waffles (Eggo)", "Pizza", "Hambúrguer", "Panquecas"], r: 0, d: 2 },
  { p: "Qual vilão aterroriza a 4ª temporada de Stranger Things?", ops: ["Vecna", "Demogorgon", "Devorador de Mentes", "Billy"], r: 0, d: 2 },
  { p: "Qual música salva a Max em Stranger Things?", ops: ["Running Up That Hill", "Should I Stay or Should I Go", "Africa", "Take On Me"], r: 0, d: 2 },
  { p: "Em Breaking Bad, qual é o negócio de fachada de Walter e Skyler?", ops: ["Um lava-rápido", "Uma lavanderia", "Uma lanchonete", "Um estacionamento"], r: 0, d: 2 },
  { p: "Em Breaking Bad, quem é o cunhado de Walter que trabalha no DEA?", ops: ["Hank", "Mike", "Gus", "Saul"], r: 0, d: 2 },
  { p: "Complete a frase de Walter White: 'Say my...'", ops: ["name", "price", "word", "rules"], r: 0, d: 2 },
  { p: "Em Game of Thrones, qual é o título de Daenerys entre os dothraki?", ops: ["Khaleesi", "Valonqar", "Sacerdotisa", "Kingslayer"], r: 0, d: 2 },
  { p: "Quem escreveu os livros que originaram Game of Thrones?", ops: ["George R.R. Martin", "J.R.R. Tolkien", "Patrick Rothfuss", "Brandon Sanderson"], r: 0, d: 2 },
  { p: "Como ficou conhecido o massacre dos Stark num casamento em GoT?", ops: ["Casamento Vermelho", "Casamento Negro", "Noite Sangrenta", "Festim dos Corvos"], r: 0, d: 2 },
  { p: "Em GoT, qual é a origem do nome 'Hodor'?", ops: ["Hold the door", "Uma oração antiga", "O nome do pai", "Um cavalo"], r: 0, d: 2 },
  { p: "Em GoT, qual é a capital dos Sete Reinos?", ops: ["Porto Real", "Winterfell", "Correrrio", "Vilavelha"], r: 0, d: 2 },
  { p: "House of the Dragon conta a história de qual casa?", ops: ["Targaryen", "Stark", "Lannister", "Baratheon"], r: 0, d: 2 },
  { p: "Em The Boys, como se chama o grupo de 'heróis' corporativos?", ops: ["Os Sete", "A Liga", "Os Vingadores", "Payback"], r: 0, d: 2 },
  { p: "Quem é o líder cruel dos Sete em The Boys?", ops: ["Capitão Pátria", "Bruto", "Trem-Bala", "Profundo"], r: 0, d: 2 },
  { p: "Em Euphoria, quem interpreta a protagonista Rue?", ops: ["Zendaya", "Sydney Sweeney", "Hunter Schafer", "Alexa Demie"], r: 0, d: 2 },
  { p: "Em You, qual é a profissão inicial de Joe Goldberg?", ops: ["Livreiro", "Professor", "Fotógrafo", "Barista"], r: 0, d: 2 },
  { p: "Em Ozark, com o que a família Byrde trabalha (ilegalmente)?", ops: ["Lavagem de dinheiro", "Contrabando de armas", "Falsificação", "Sequestros"], r: 0, d: 2 },
  { p: "Em Lupin, o protagonista se inspira em qual personagem literário?", ops: ["Arsène Lupin", "Sherlock Holmes", "Fantômas", "Robin Hood"], r: 0, d: 2 },
  { p: "Em The Queen's Gambit, qual é o vício de Beth?", ops: ["Tranquilizantes", "Cigarro", "Jogo de azar", "Café"], r: 0, d: 2 },
  { p: "Quem interpreta Joel em The Last of Us?", ops: ["Pedro Pascal", "Oscar Isaac", "Diego Luna", "Javier Bardem"], r: 0, d: 2 },
  { p: "Quem interpreta Thomas Shelby em Peaky Blinders?", ops: ["Cillian Murphy", "Tom Hardy", "Paul Anderson", "Joe Cole"], r: 0, d: 2 },
  { p: "O que os Peaky Blinders escondem nas boinas?", ops: ["Lâminas", "Moedas", "Cartas de baralho", "Fósforos"], r: 0, d: 2 },
  { p: "Better Call Saul: qual é o nome verdadeiro de Saul Goodman?", ops: ["Jimmy McGill", "Charles McGill", "Howard Hamlin", "Gene Takovic"], r: 0, d: 2 },
  { p: "Em Dexter, qual é a profissão 'oficial' do protagonista?", ops: ["Analista de sangue forense", "Detetive", "Legista", "Promotor"], r: 0, d: 2 },
  { p: "Em Suits, qual é o segredo de Mike Ross?", ops: ["Nunca cursou Direito", "É filho do sócio", "Era policial", "Tem outra identidade"], r: 0, d: 2 },
  { p: "Qual personagem Meghan Markle interpretava em Suits?", ops: ["Rachel Zane", "Donna Paulsen", "Jessica Pearson", "Katrina Bennett"], r: 0, d: 2 },
  { p: "Em How to Get Away with Murder, quem é a professora de Direito?", ops: ["Annalise Keating", "Olivia Pope", "Miranda Bailey", "Diane Lockhart"], r: 0, d: 2 },
  { p: "Quem interpreta Pablo Escobar em Narcos?", ops: ["Wagner Moura", "Diego Luna", "Gael García", "Rodrigo Santoro"], r: 0, d: 2 },
  { p: "Em Lost, quais são os números misteriosos?", ops: ["4 8 15 16 23 42", "1 2 3 5 8 13", "7 11 23 42 66 99", "3 6 9 12 15 18"], r: 0, d: 2 },
  { p: "Em Lost, qual organização científica tinha estações na ilha?", ops: ["Iniciativa Dharma", "Projeto Manhattan", "Umbrella", "Hanso Corp"], r: 0, d: 2 },
  { p: "Em Westworld, o parque é povoado por...", ops: ["androides", "clones", "fantasmas", "atores"], r: 0, d: 2 },
  { p: "Quem forma a dupla da 1ª temporada de True Detective?", ops: ["McConaughey e Harrelson", "Pitt e Freeman", "Farrell e Vaughn", "Ali e Dorff"], r: 0, d: 2 },
  { p: "Em Mindhunter, os agentes do FBI entrevistam...", ops: ["serial killers", "espiões", "hackers", "mafiosos"], r: 0, d: 2 },
  { p: "Em Bones, qual é a especialidade da Dra. Brennan?", ops: ["Antropologia forense", "Patologia", "Psiquiatria", "Odontologia legal"], r: 0, d: 2 },
  { p: "Em Criminal Minds, o que significa a unidade 'BAU'?", ops: ["Análise Comportamental", "Busca e Apreensão", "Balística Avançada", "Brigada Antiterror"], r: 0, d: 2 },
  { p: "Law & Order: SVU é comandada por qual detetive icônica?", ops: ["Olivia Benson", "Kate Beckett", "Jane Rizzoli", "Clarice Starling"], r: 0, d: 2 },
  { p: "Em Desperate Housewives, qual é o nome da rua?", ops: ["Wisteria Lane", "Elm Street", "Maple Drive", "Mulberry Lane"], r: 0, d: 2 },
  { p: "Em Killing Eve, qual é o nome da assassina estilosa?", ops: ["Villanelle", "Eve", "Carolyn", "Konstantin"], r: 0, d: 2 },
  { p: "Em The Marvelous Mrs. Maisel, qual carreira Midge persegue?", ops: ["Comediante de stand-up", "Cantora", "Atriz", "Jornalista"], r: 0, d: 2 },
  { p: "Em Fleabag, por quem a protagonista se apaixona na 2ª temporada?", ops: ["Um padre", "O cunhado", "O advogado", "O terapeuta"], r: 0, d: 2 },
  { p: "Em This Is Us, como os irmãos se chamam coletivamente?", ops: ["Big Three", "Triplets", "Pearson Trio", "The Three"], r: 0, d: 2 },
  { p: "Em This Is Us, a morte de Jack está ligada a...", ops: ["um incêndio", "um acidente de carro", "um assalto", "uma doença"], r: 0, d: 2 },
  { p: "Em Shameless (EUA), qual é o sobrenome da família?", ops: ["Gallagher", "Fisher", "Milkovich", "Ball"], r: 0, d: 2 },
  { p: "Em Lucifer, o dono da boate ajuda qual instituição?", ops: ["A polícia de Los Angeles", "O FBI", "A prefeitura", "Um hospital"], r: 0, d: 2 },
  { p: "Em The Vampire Diaries, quem são os irmãos vampiros?", ops: ["Damon e Stefan", "Sam e Dean", "Klaus e Elijah", "Edward e Emmett"], r: 0, d: 2 },
  { p: "Em Anne with an E, como se chama a propriedade dos Cuthbert?", ops: ["Green Gables", "Tara", "Downton", "Avonlea Farm"], r: 0, d: 2 },
  { p: "Em Outlander, Claire viaja no tempo para...", ops: ["a Escócia do século 18", "a França revolucionária", "a Roma antiga", "o Velho Oeste"], r: 0, d: 2 },
  { p: "Em Gilmore Girls, o que o Luke tem na cidade?", ops: ["Uma lanchonete", "Uma livraria", "Uma pousada", "Uma oficina"], r: 0, d: 2 },
  { p: "Bridgerton se passa em qual período?", ops: ["Regência inglesa", "Era vitoriana", "Renascimento", "Anos 1920"], r: 0, d: 2 },
  { p: "Qual casal protagoniza a 1ª temporada de Bridgerton?", ops: ["Daphne e Simon", "Anthony e Kate", "Colin e Penelope", "Benedict e Sophie"], r: 0, d: 2 },
  { p: "Em Round 6, quais formas aparecem nos cartões-convite?", ops: ["Círculo, triângulo e quadrado", "Estrela, lua e sol", "Cruz, coração e losango", "Seta, cubo e esfera"], r: 0, d: 2 },
  { p: "Em The Umbrella Academy, os irmãos foram adotados por...", ops: ["um bilionário excêntrico", "uma agência secreta", "um circo", "uma cientista"], r: 0, d: 2 },
  { p: "Em 13 Reasons Why, o que Hannah deixa para trás?", ops: ["13 fitas cassete", "13 cartas", "13 e-mails", "13 vídeos"], r: 0, d: 2 },
  { p: "Homeland acompanha uma agente de qual órgão?", ops: ["CIA", "FBI", "NSA", "MI6"], r: 0, d: 2 },
  { p: "Em Ted Lasso, qual é o nome do time?", ops: ["AFC Richmond", "West Ham", "FC Nelson", "Richmond Rovers"], r: 0, d: 2 },
  { p: "Qual palavra fica na plaquinha do vestiário em Ted Lasso?", ops: ["Believe", "Win", "Family", "Together"], r: 0, d: 2 },
  { p: "Qual é o bordão de The Mandalorian?", ops: ["This is the way", "May the force", "So say we all", "Winter is coming"], r: 0, d: 2 },
  { p: "Em Downton Abbey, qual é o nome do mordomo-chefe?", ops: ["Carson", "Bates", "Barrow", "Molesley"], r: 0, d: 2 },
  { p: "Quem interpreta a Condessa Viúva em Downton Abbey?", ops: ["Maggie Smith", "Judi Dench", "Helen Mirren", "Emma Thompson"], r: 0, d: 2 },
  { p: "Quem interpretou Tony Soprano?", ops: ["James Gandolfini", "Al Pacino", "Ray Liotta", "Joe Pesci"], r: 0, d: 2 },
  { p: "Em Sherlock, quem é o grande vilão rival do detetive?", ops: ["Moriarty", "Mycroft", "Magnussen", "Lestrade"], r: 0, d: 2 },
  { p: "Black Mirror teve um filme interativo chamado...", ops: ["Bandersnatch", "San Junipero", "White Bear", "Playtest"], r: 0, d: 2 },
  { p: "Em Sense8, quantas pessoas formam o 'cluster'?", ops: ["8", "6", "7", "12"], r: 0, d: 2 },
  { p: "Em Smallville, quem é o protagonista adolescente?", ops: ["Clark Kent", "Bruce Wayne", "Barry Allen", "Oliver Queen"], r: 0, d: 2 },
  { p: "Qual carro clássico os irmãos dirigem em Supernatural?", ops: ["Chevrolet Impala", "Ford Mustang", "Dodge Charger", "Camaro"], r: 0, d: 2 },
  { p: "Drive to Survive mostra os bastidores de qual esporte?", ops: ["Fórmula 1", "MotoGP", "NASCAR", "Rali"], r: 0, d: 2 },
  { p: "The Last Dance conta a história de qual atleta?", ops: ["Michael Jordan", "Kobe Bryant", "LeBron James", "Magic Johnson"], r: 0, d: 2 },

  // ---------- nível 3 ----------
  { p: "Quem cria e estrela Fleabag?", ops: ["Phoebe Waller-Bridge", "Michaela Coel", "Sharon Horgan", "Aisling Bea"], r: 0, d: 3 },
  { p: "The Wire se passa em qual cidade americana?", ops: ["Baltimore", "Detroit", "Chicago", "Filadélfia"], r: 0, d: 3 },
  { p: "Qual pergunta move a trama de Twin Peaks?", ops: ["Quem matou Laura Palmer?", "Onde está Audrey?", "Quem é Bob?", "O que há na floresta?"], r: 0, d: 3 },
  { p: "Quem interpreta a rainha nas duas primeiras temporadas de The Crown?", ops: ["Claire Foy", "Olivia Colman", "Imelda Staunton", "Vanessa Kirby"], r: 0, d: 3 },
  { p: "Em The Sopranos, qual é o nome da psiquiatra de Tony?", ops: ["Dra. Melfi", "Dra. Skyler", "Dra. Marchetti", "Dra. Bruni"], r: 0, d: 3 },
  { p: "Em Severance, qual é o nome da empresa misteriosa?", ops: ["Lumon", "Hooli", "Initech", "Vought"], r: 0, d: 3 },
  { p: "Em Plantão Médico (ER), George Clooney interpretava...", ops: ["Dr. Doug Ross", "Dr. Mark Greene", "Dr. John Carter", "Dr. Peter Benton"], r: 0, d: 3 },
  { p: "Plantão Médico (ER) se passa em qual hospital?", ops: ["County General", "Chicago Med", "St. Elsewhere", "Mercy"], r: 0, d: 3 },
  { p: "Em House, qual é o nome do hospital?", ops: ["Princeton-Plainsboro", "Seattle Grace", "New Amsterdam", "Chastain"], r: 0, d: 3 },
  { p: "Qual analgésico o Dr. House consome compulsivamente?", ops: ["Vicodin", "Morfina", "Tramadol", "Oxicodona"], r: 0, d: 3 },
  { p: "Quem é o melhor (e único) amigo do Dr. House?", ops: ["Dr. Wilson", "Dr. Chase", "Dr. Foreman", "Dr. Taub"], r: 0, d: 3 },
  { p: "Qual é o lema do Dr. House?", ops: ["Todo mundo mente", "Confie em mim", "A dor ensina", "Nunca é lúpus... às vezes é"], r: 0, d: 3 },
  { p: "Em Grey's Anatomy, qual meia-irmã de Meredith morre no acidente aéreo?", ops: ["Lexie", "Maggie", "Amelia", "Molly"], r: 0, d: 3 },
  { p: "Para qual cidade Cristina Yang se muda ao sair de Grey's?", ops: ["Zurique", "Genebra", "Boston", "Minneapolis"], r: 0, d: 3 },
  { p: "Quem criou Grey's Anatomy?", ops: ["Shonda Rhimes", "Ryan Murphy", "Marta Kauffman", "Amy Sherman-Palladino"], r: 0, d: 3 },
  { p: "Em Grey's Anatomy, qual era o apelido do George O'Malley?", ops: ["007", "Bambi", "McClumsy", "Riacho"], r: 0, d: 3 },
  { p: "Em Scrubs, qual é o nome do hospital?", ops: ["Sacred Heart", "St. Bonaventure", "All Saints", "Holy Cross"], r: 0, d: 3 },
  { p: "Em New Amsterdam, qual é o bordão do Dr. Max Goodwin?", ops: ["Como posso ajudar?", "Confie no processo", "Sem burocracia", "Vamos curar"], r: 0, d: 3 },
  { p: "Em Friends, qual é o nome da gêmea da Phoebe?", ops: ["Ursula", "Amanda", "Regina", "Estelle"], r: 0, d: 3 },
  { p: "Em Friends, com o que exatamente Chandler trabalha?", ops: ["Análise estatística e reconfiguração de dados", "Publicidade", "Contabilidade", "TI corporativa"], r: 0, d: 3 },
  { p: "Em The Office, onde Jim e Pam se casam?", ops: ["Cataratas do Niágara", "Scranton", "Nova York", "Poconos"], r: 0, d: 3 },
  { p: "Em The Office, Ryan começou na empresa como...", ops: ["temporário", "estagiário de vendas", "gerente", "contador"], r: 0, d: 3 },
  { p: "Quem canta a música-tema de The Big Bang Theory?", ops: ["Barenaked Ladies", "Weezer", "They Might Be Giants", "Fountains of Wayne"], r: 0, d: 3 },
  { p: "Em Parks and Recreation, em que cidade fictícia Leslie trabalha?", ops: ["Pawnee", "Eagleton", "Partridge", "Greendale"], r: 0, d: 3 },
  { p: "Quem interpreta Michael em The Good Place?", ops: ["Ted Danson", "Steve Martin", "Bill Murray", "Martin Short"], r: 0, d: 3 },
  { p: "Em Dark, qual é o intervalo dos ciclos de viagem no tempo?", ops: ["33 anos", "25 anos", "50 anos", "13 anos"], r: 0, d: 3 },
  { p: "Em GoT, quais são os nomes dos três dragões?", ops: ["Drogon, Rhaegal e Viserion", "Balerion, Meraxes e Vhagar", "Drogon, Vermax e Arrax", "Syrax, Caraxes e Meleys"], r: 0, d: 3 },
  { p: "Em Succession, quantos filhos Logan Roy tem?", ops: ["4", "3", "2", "5"], r: 0, d: 3 },
  { p: "Em Succession, qual rap Kendall 'apresenta' para o pai?", ops: ["L to the OG", "Roy Boy", "Number One Son", "Waystar Flow"], r: 0, d: 3 },
  { p: "Quem interpreta a princesa Diana na 4ª temporada de The Crown?", ops: ["Emma Corrin", "Elizabeth Debicki", "Vanessa Kirby", "Erin Doherty"], r: 0, d: 3 },
  { p: "Em Breaking Bad, quem é o chefão que se esconde atrás de uma rede de frango frito?", ops: ["Gus Fring", "Tuco", "Don Eladio", "Hector"], r: 0, d: 3 },
  { p: "Better Call Saul: qual é o nome do irmão de Jimmy?", ops: ["Chuck", "Howard", "Gene", "Marco"], r: 0, d: 3 },
  { p: "Em Ozark, em qual estado fica o lago da família Byrde?", ops: ["Missouri", "Arkansas", "Kentucky", "Tennessee"], r: 0, d: 3 },
  { p: "Quem interpreta Assane Diop em Lupin?", ops: ["Omar Sy", "Idris Elba", "John Boyega", "Tahar Rahim"], r: 0, d: 3 },
  { p: "Em Elite, qual é o nome do colégio?", ops: ["Las Encinas", "San Esteban", "El Internado", "Los Robles"], r: 0, d: 3 },
  { p: "Em Big Little Lies, em qual cidade litorânea vivem as protagonistas?", ops: ["Monterey", "Malibu", "Santa Cruz", "Carmel"], r: 0, d: 3 },
  { p: "Em Mad Men, como se chama a agência no início da série?", ops: ["Sterling Cooper", "Draper & Price", "McCann Erickson", "Cutler Gleason"], r: 0, d: 3 },
  { p: "Em Mad Men, Peggy começa na agência como...", ops: ["secretária", "redatora", "recepcionista", "assistente de arte"], r: 0, d: 3 },
  { p: "Quem dá voz à narradora de Gossip Girl?", ops: ["Kristen Bell", "Blake Lively", "Leighton Meester", "America Ferrera"], r: 0, d: 3 },
  { p: "Em Desperate Housewives, quem narra a série?", ops: ["Mary Alice", "Susan", "Bree", "Gabrielle"], r: 0, d: 3 },
  { p: "Em Sex and the City, qual é a marca de sapatos favorita de Carrie?", ops: ["Manolo Blahnik", "Jimmy Choo", "Louboutin", "Prada"], r: 0, d: 3 },
  { p: "Em The Vampire Diaries, como se chama a cidade?", ops: ["Mystic Falls", "Forks", "Bon Temps", "Beacon Hills"], r: 0, d: 3 },
  { p: "The O.C. se passa em qual condado?", ops: ["Orange County", "Los Angeles", "San Diego", "Ventura"], r: 0, d: 3 },
  { p: "Em Two and a Half Men, qual era a profissão de Charlie Harper?", ops: ["Compositor de jingles", "Ator", "Produtor musical", "DJ"], r: 0, d: 3 },
  { p: "Band of Brothers acompanha qual companhia na 2ª Guerra?", ops: ["Companhia Easy", "Companhia Alpha", "Companhia Bravo", "Companhia Dog"], r: 0, d: 3 },
  { p: "Em Chernobyl, quem é o cientista interpretado por Jared Harris?", ops: ["Valery Legasov", "Boris Shcherbina", "Ulana Khomyuk", "Anatoly Dyatlov"], r: 0, d: 3 },
  { p: "Qual episódio de Black Mirror ganhou o Emmy com um amor nos anos 80 virtuais?", ops: ["San Junipero", "Nosedive", "Hang the DJ", "White Christmas"], r: 0, d: 3 },
  { p: "Em The Morning Show, quem interpreta a apresentadora Alex Levy?", ops: ["Jennifer Aniston", "Reese Witherspoon", "Nicole Kidman", "Laura Dern"], r: 0, d: 3 },
  { p: "Em Vikings, qual monge vira amigo de Ragnar?", ops: ["Athelstan", "Ecbert", "Alfred", "Cuthbert"], r: 0, d: 3 },
  { p: "Em Ted Lasso, qual jogador aposentado rabugento vira técnico?", ops: ["Roy Kent", "Jamie Tartt", "Dani Rojas", "Isaac McAdoo"], r: 0, d: 3 },
  { p: "Qual ator deixou The Witcher após a 3ª temporada?", ops: ["Henry Cavill", "Liam Hemsworth", "Tom Hopper", "Charlie Hunnam"], r: 0, d: 3 },
  { p: "Na 1ª temporada de La Casa de Papel, qual é o alvo do assalto?", ops: ["A Casa da Moeda", "O Banco da Espanha", "O Museu do Prado", "A Bolsa de Madri"], r: 0, d: 3 },
  { p: "Em Wandinha, qual música embala a dança viral?", ops: ["Goo Goo Muck", "Bloody Mary", "Paint It Black", "Psycho Killer"], r: 0, d: 3 },
  { p: "Em Gilmore Girls, em qual universidade Rory estuda?", ops: ["Yale", "Harvard", "Princeton", "Columbia"], r: 0, d: 3 },
  { p: "Em CSI original, qual é a cidade-sede?", ops: ["Las Vegas", "Miami", "Nova York", "Los Angeles"], r: 0, d: 3 },
  { p: "Em The Blacklist, qual é o nome do criminoso que se entrega ao FBI?", ops: ["Raymond Reddington", "Tom Keen", "Alan Fitch", "Berlin"], r: 0, d: 3 },
  { p: "Em Homeland, qual transtorno a agente Carrie esconde?", ops: ["Bipolaridade", "TOC", "Esquizofrenia", "Pânico"], r: 0, d: 3 },
  { p: "Quais agentes do DEA caçam Escobar em Narcos?", ops: ["Peña e Murphy", "Crockett e Tubbs", "Hank e Gomez", "Riggs e Murtaugh"], r: 0, d: 3 },
  { p: "Em Dexter, em qual cidade ele 'trabalha'?", ops: ["Miami", "Tampa", "Nova Orleans", "Houston"], r: 0, d: 3 },
  { p: "Em Lost, o que a fumaça negra da ilha era?", ops: ["O Homem de Preto", "Um experimento Dharma", "Nanorrobôs", "Um deus antigo"], r: 0, d: 3 }
];
