// Banco de perguntas — ITÁLIA (~120). { p, ops[4], r, d }
// Revise as difíceis (d:3) — edite/apague livremente.
window.QUIZ = window.QUIZ || {};
window.QUIZ.italia = [
  // ---------- nível 1 ----------
  { p: "Qual é a capital da Itália?", ops: ["Milão", "Roma", "Florença", "Nápoles"], r: 1, d: 1 },
  { p: "Em qual fonte de Roma se joga moeda para voltar à cidade?", ops: ["Fontana di Trevi", "Fontana del Moro", "Quattro Fiumi", "Barcaccia"], r: 0, d: 1 },
  { p: "O Coliseu era palco principalmente de quê?", ops: ["Corridas de biga", "Peças de teatro", "Lutas de gladiadores", "Julgamentos"], r: 2, d: 1 },
  { p: "O Vaticano é famoso por ser...", ops: ["o menor país do mundo", "uma província romana", "um bairro de Roma", "uma ilha"], r: 0, d: 1 },
  { p: "Em qual cidade fica a famosa torre inclinada?", ops: ["Siena", "Bolonha", "Pisa", "Verona"], r: 2, d: 1 },
  { p: "Qual cidade italiana é conhecida pelos canais e gôndolas?", ops: ["Gênova", "Veneza", "Trieste", "Bari"], r: 1, d: 1 },
  { p: "A Sardenha é...", ops: ["uma península", "uma ilha", "uma região alpina", "uma cidade"], r: 1, d: 1 },
  { p: "As cores da pizza margherita homenageiam...", ops: ["a rainha da Áustria", "a bandeira italiana", "o Vaticano", "a cidade de Nápoles"], r: 1, d: 1 },
  { p: "Qual vulcão fica perto de Nápoles?", ops: ["Etna", "Stromboli", "Vesúvio", "Vulcano"], r: 2, d: 1 },
  { p: "Qual cidade romana foi soterrada pelo Vesúvio em 79 d.C.?", ops: ["Óstia", "Pompeia", "Cápua", "Ravena"], r: 1, d: 1 },
  { p: "Quem pintou o teto da Capela Sistina?", ops: ["Rafael", "Michelangelo", "Da Vinci", "Caravaggio"], r: 1, d: 1 },
  { p: "Segundo a lenda, Roma foi fundada por...", ops: ["Júlio César", "Rômulo e Remo", "Enéas", "Augusto"], r: 1, d: 1 },
  { p: "Qual aperitivo italiano leva Aperol e prosecco?", ops: ["Negroni", "Bellini", "Spritz", "Campari tônica"], r: 2, d: 1 },
  { p: "A bandeira da Itália é verde, branca e...", ops: ["azul", "amarela", "vermelha", "preta"], r: 2, d: 1 },
  { p: "A Vespa é uma clássica marca italiana de...", ops: ["bicicleta", "lambreta", "carro esporte", "barco"], r: 1, d: 1 },
  { p: "Qual é o formato da Itália no mapa?", ops: ["Uma bota", "Uma luva", "Um sapato", "Uma âncora"], r: 0, d: 1 },
  { p: "Qual é o apelido de Roma?", ops: ["Cidade Eterna", "Cidade Luz", "Cidade Maravilhosa", "Cidade dos Papas"], r: 0, d: 1 },
  { p: "'Ciao' em italiano serve para...", ops: ["oi e tchau", "só oi", "só tchau", "bom dia"], r: 0, d: 1 },
  { p: "O que significa 'grazie'?", ops: ["Obrigado(a)", "De nada", "Por favor", "Desculpa"], r: 0, d: 1 },
  { p: "O que significa 'nonna'?", ops: ["Avó", "Mãe", "Tia", "Madrinha"], r: 0, d: 1 },
  { p: "Massa 'al dente' é massa...", ops: ["cozida mas firme ao morder", "bem molinha", "crua", "gratinada"], r: 0, d: 1 },
  { p: "Qual sobremesa italiana leva café e mascarpone?", ops: ["Tiramisù", "Panna cotta", "Cannolo", "Zabaione"], r: 0, d: 1 },
  { p: "Milão é a capital italiana de qual indústria?", ops: ["Moda", "Vinho", "Automóveis", "Cinema"], r: 0, d: 1 },
  { p: "Qual cidade é o cenário de Romeu e Julieta?", ops: ["Verona", "Veneza", "Florença", "Pádua"], r: 0, d: 1 },
  { p: "A pizza nasceu em qual cidade italiana?", ops: ["Nápoles", "Roma", "Milão", "Palermo"], r: 0, d: 1 },
  { p: "'Andiamo!' significa...", ops: ["Vamos!", "Pare!", "Espere!", "Corra!"], r: 0, d: 1 },
  { p: "Qual é a moeda da Itália?", ops: ["Euro", "Lira", "Florim", "Franco"], r: 0, d: 1 },

  // ---------- nível 2 ----------
  { p: "A Puglia fica em qual parte da Itália?", ops: ["No 'salto da bota', ao sul", "No norte", "No centro", "Na costa oeste"], r: 0, d: 2 },
  { p: "Onde ficam os trulli, as casinhas cônicas da Puglia?", ops: ["Alberobello", "Ostuni", "Lecce", "Matera"], r: 0, d: 2 },
  { p: "Qual costa da Sardenha é famosa pelo mar verde-esmeralda?", ops: ["Costa Esmeralda", "Costa Amalfitana", "Cinque Terre", "Riviera Ligure"], r: 0, d: 2 },
  { p: "Qual massa em formato de 'orelhinha' é típica da Puglia?", ops: ["Orecchiette", "Farfalle", "Trofie", "Cavatelli"], r: 0, d: 2 },
  { p: "Em qual cidade está o Davi de Michelangelo?", ops: ["Florença", "Roma", "Milão", "Turim"], r: 0, d: 2 },
  { p: "O que significa 'dolce far niente'?", ops: ["O doce prazer de não fazer nada", "Doce da tarde", "Comer devagar", "Vida doce e curta"], r: 0, d: 2 },
  { p: "Para o italiano tradicional, pedir cappuccino depois do almoço é...", ops: ["coisa de turista", "obrigatório", "sinal de elegância", "proibido por lei"], r: 0, d: 2 },
  { p: "Qual rio corta a cidade de Roma?", ops: ["Tibre", "Arno", "Pó", "Ádige"], r: 0, d: 2 },
  { p: "Cacio e pepe é uma massa típica de qual cidade?", ops: ["Roma", "Milão", "Bolonha", "Palermo"], r: 0, d: 2 },
  { p: "A burrata nasceu em qual região italiana?", ops: ["Puglia", "Toscana", "Sicília", "Ligúria"], r: 0, d: 2 },
  { p: "A Costa Amalfitana fica perto de qual cidade?", ops: ["Nápoles", "Gênova", "Veneza", "Bari"], r: 0, d: 2 },
  { p: "Segundo a lenda, a Bocca della Verità em Roma...", ops: ["morde a mão de quem mente", "realiza desejos", "prevê o futuro", "cura doenças"], r: 0, d: 2 },
  { p: "Trastevere é...", ops: ["um bairro charmoso de Roma", "um vinho", "uma praça de Milão", "um tipo de massa"], r: 0, d: 2 },
  { p: "O spaghetti alla carbonara clássico leva ovos, pecorino e...", ops: ["guanciale", "bacon", "presunto", "linguiça"], r: 0, d: 2 },
  { p: "Na receita tradicional, a carbonara leva creme de leite?", ops: ["Não, jamais", "Sim, sempre", "Só no inverno", "Depende da região"], r: 0, d: 2 },
  { p: "O pesto genovês tem como base qual erva?", ops: ["Manjericão", "Salsa", "Orégano", "Alecrim"], r: 0, d: 2 },
  { p: "O risoto é típico de qual parte da Itália?", ops: ["Norte", "Sul", "Sicília", "Sardenha"], r: 0, d: 2 },
  { p: "O presunto cru mais famoso da Itália vem de...", ops: ["Parma", "Roma", "Nápoles", "Veneza"], r: 0, d: 2 },
  { p: "O panetone nasceu em qual cidade?", ops: ["Milão", "Turim", "Roma", "Verona"], r: 0, d: 2 },
  { p: "O limoncello é feito com limões de qual região?", ops: ["Costa Amalfitana", "Toscana", "Piemonte", "Vêneto"], r: 0, d: 2 },
  { p: "O Chianti é um vinho de qual região?", ops: ["Toscana", "Puglia", "Sicília", "Lombardia"], r: 0, d: 2 },
  { p: "Arancini (bolinhos de arroz) são típicos de onde?", ops: ["Sicília", "Roma", "Milão", "Gênova"], r: 0, d: 2 },
  { p: "Cannoli recheados de ricota são a cara de qual região?", ops: ["Sicília", "Puglia", "Vêneto", "Emília"], r: 0, d: 2 },
  { p: "O aperitivo italiano acontece tradicionalmente...", ops: ["antes do jantar", "depois do jantar", "no café da manhã", "à meia-noite"], r: 0, d: 2 },
  { p: "Como o italiano tradicional toma o espresso no bar?", ops: ["Em pé, no balcão", "Sentado, devagar", "Para viagem", "Com canudo"], r: 0, d: 2 },
  { p: "Roma foi construída sobre quantas colinas?", ops: ["7", "5", "9", "3"], r: 0, d: 2 },
  { p: "O Circo Massimo recebia qual espetáculo?", ops: ["Corridas de biga", "Lutas de gladiadores", "Peças", "Execuções"], r: 0, d: 2 },
  { p: "A Escadaria Espanhola desce para qual praça?", ops: ["Piazza di Spagna", "Piazza Navona", "Campo de' Fiori", "Piazza del Popolo"], r: 0, d: 2 },
  { p: "Qual guarda protege o Vaticano?", ops: ["Guarda Suíça", "Guarda Real", "Carabinieri", "Legião Romana"], r: 0, d: 2 },
  { p: "Qual evento acontece na Capela Sistina quando morre um papa?", ops: ["O conclave", "A canonização", "O jubileu", "A vigília"], r: 0, d: 2 },
  { p: "Júlio César foi assassinado nos 'idos de...'", ops: ["março", "janeiro", "agosto", "dezembro"], r: 0, d: 2 },
  { p: "Qual animal amamentou Rômulo e Remo na lenda?", ops: ["Uma loba", "Uma ursa", "Uma águia", "Uma cabra"], r: 0, d: 2 },
  { p: "Quais são os dois times de futebol de Roma?", ops: ["Roma e Lazio", "Roma e Napoli", "Lazio e Juventus", "Roma e Inter"], r: 0, d: 2 },
  { p: "O Renascimento nasceu em qual cidade?", ops: ["Florença", "Roma", "Veneza", "Milão"], r: 0, d: 2 },
  { p: "A Mona Lisa de Da Vinci está exposta em...", ops: ["Paris (Louvre)", "Roma", "Florença", "Milão"], r: 0, d: 2 },
  { p: "Dante Alighieri escreveu qual obra-prima?", ops: ["A Divina Comédia", "O Príncipe", "Decamerão", "Orlando Furioso"], r: 0, d: 2 },
  { p: "O teatro de ópera La Scala fica em...", ops: ["Milão", "Roma", "Nápoles", "Veneza"], r: 0, d: 2 },
  { p: "Luciano Pavarotti era um famoso...", ops: ["tenor", "maestro", "barítono", "pianista"], r: 0, d: 2 },
  { p: "Enzo Ferrari fundou a Ferrari em qual região?", ops: ["Emília-Romanha", "Toscana", "Piemonte", "Lácio"], r: 0, d: 2 },
  { p: "Gucci, Prada e Armani são marcas italianas de...", ops: ["moda", "carros", "vinhos", "móveis"], r: 0, d: 2 },
  { p: "A Juventus é o time de qual cidade?", ops: ["Turim", "Milão", "Roma", "Gênova"], r: 0, d: 2 },
  { p: "Qual é o apelido da seleção italiana de futebol?", ops: ["Azzurra", "Verdeoro", "Furia", "Nerazzurra"], r: 0, d: 2 },
  { p: "Cinque Terre são cinco vilarejos coloridos de qual região?", ops: ["Ligúria", "Toscana", "Campânia", "Puglia"], r: 0, d: 2 },
  { p: "Capri é famosa por qual atração natural?", ops: ["Gruta Azul", "Gêiseres", "Cachoeiras", "Dunas"], r: 0, d: 2 },
  { p: "San Marino e Vaticano têm o que em comum?", ops: ["São países dentro da Itália", "São ilhas", "São regiões do sul", "São capitais antigas"], r: 0, d: 2 },
  { p: "Positano e Amalfi são vilarejos de qual costa?", ops: ["Amalfitana", "Esmeralda", "Adriática", "Lígure"], r: 0, d: 2 },
  { p: "O Carnaval de Veneza é famoso por...", ops: ["máscaras e fantasias de época", "desfiles de escolas", "batalhas de flores", "fogos na lagoa"], r: 0, d: 2 },
  { p: "A capital da Toscana é...", ops: ["Florença", "Pisa", "Siena", "Lucca"], r: 0, d: 2 },
  { p: "A capital da Puglia é...", ops: ["Bari", "Lecce", "Brindisi", "Taranto"], r: 0, d: 2 },
  { p: "Quais dois vulcões italianos seguem ativos?", ops: ["Etna e Vesúvio", "Etna e Monte Bianco", "Vesúvio e Apeninos", "Stromboli e Alpes"], r: 0, d: 2 },

  // ---------- nível 3 ----------
  { p: "O Panteão de Roma é famoso por qual detalhe da cúpula?", ops: ["O óculo aberto no topo", "Os vitrais", "O mosaico dourado", "As gárgulas"], r: 0, d: 3 },
  { p: "Roma fica em qual região da Itália?", ops: ["Lácio", "Toscana", "Úmbria", "Campânia"], r: 0, d: 3 },
  { p: "Em qual cidade fica a sede da Ferrari?", ops: ["Maranello", "Módena", "Bolonha", "Monza"], r: 0, d: 3 },
  { p: "Matera, vizinha da Puglia, é famosa por...", ops: ["casas escavadas na rocha (Sassi)", "canais", "termas romanas", "vinhedos"], r: 0, d: 3 },
  { p: "Lecce, na Puglia, é apelidada de...", ops: ["'Florença do Sul'", "'Veneza do Sul'", "'Roma Pequena'", "'Pérola do Adriático'"], r: 0, d: 3 },
  { p: "Além do italiano, qual língua histórica se fala na Sardenha?", ops: ["Sardo", "Catalão antigo", "Grego", "Occitano"], r: 0, d: 3 },
  { p: "Qual é o nome oficial do Coliseu?", ops: ["Anfiteatro Flavio", "Arena Máxima", "Teatro de Nero", "Anfiteatro de Augusto"], r: 0, d: 3 },
  { p: "O que significa a sigla romana SPQR?", ops: ["O Senado e o Povo Romano", "Sob Proteção da Rainha", "Sete Príncipes de Roma", "Salve o Poder Romano"], r: 0, d: 3 },
  { p: "Em que ano lendário Roma teria sido fundada?", ops: ["753 a.C.", "509 a.C.", "27 a.C.", "1000 a.C."], r: 0, d: 3 },
  { p: "Para onde vão as moedas jogadas na Fontana di Trevi?", ops: ["Para caridade", "Para o Vaticano", "Para a prefeitura", "Ficam no fundo"], r: 0, d: 3 },
  { p: "Qual estrada romana antiga é a mais famosa?", ops: ["Via Ápia", "Via Aurélia", "Via Flamínia", "Via Cássia"], r: 0, d: 3 },
  { p: "A Itália é dividida em quantas regiões?", ops: ["20", "15", "25", "18"], r: 0, d: 3 },
  { p: "Qual é o maior lago da Itália?", ops: ["Garda", "Como", "Maggiore", "Trasimeno"], r: 0, d: 3 },
  { p: "Qual é o rio mais longo da Itália?", ops: ["Pó", "Tibre", "Arno", "Ádige"], r: 0, d: 3 },
  { p: "Quais mares banham a Itália?", ops: ["Tirreno, Adriático e Jônico", "Egeu, Tirreno e Negro", "Adriático, Báltico e Jônico", "Mediterrâneo apenas"], r: 0, d: 3 },
  { p: "Napoleão foi exilado (na 1ª vez) em qual ilha italiana?", ops: ["Elba", "Capri", "Ísquia", "Sicília"], r: 0, d: 3 },
  { p: "As Dolomitas ficam em qual parte da Itália?", ops: ["Nordeste (Alpes)", "Sul", "Sardenha", "Centro"], r: 0, d: 3 },
  { p: "Milão fica em qual região?", ops: ["Lombardia", "Vêneto", "Piemonte", "Ligúria"], r: 0, d: 3 },
  { p: "A capital da Sicília é...", ops: ["Palermo", "Catânia", "Messina", "Siracusa"], r: 0, d: 3 },
  { p: "A capital da Sardenha é...", ops: ["Cagliari", "Sassari", "Olbia", "Nuoro"], r: 0, d: 3 },
  { p: "A Última Ceia de Da Vinci está em qual cidade?", ops: ["Milão", "Roma", "Florença", "Veneza"], r: 0, d: 3 },
  { p: "'O Nascimento de Vênus' de Botticelli está em qual museu?", ops: ["Uffizi (Florença)", "Vaticano", "Brera (Milão)", "Borghese (Roma)"], r: 0, d: 3 },
  { p: "A língua italiana moderna deriva principalmente do dialeto...", ops: ["toscano", "romano", "vêneto", "siciliano"], r: 0, d: 3 },
  { p: "Federico Fellini dirigiu qual clássico com cena na Fontana di Trevi?", ops: ["La Dolce Vita", "Cinema Paradiso", "8½", "Amarcord"], r: 0, d: 3 },
  { p: "Cinecittà, o polo do cinema italiano, fica em...", ops: ["Roma", "Milão", "Turim", "Nápoles"], r: 0, d: 3 },
  { p: "A Lamborghini começou fabricando...", ops: ["tratores", "motos", "aviões", "barcos"], r: 0, d: 3 },
  { p: "A Fiat nasceu em qual cidade?", ops: ["Turim", "Milão", "Bolonha", "Gênova"], r: 0, d: 3 },
  { p: "Milan e Inter dividem qual estádio?", ops: ["San Siro", "Olimpico", "Juventus Stadium", "Marassi"], r: 0, d: 3 },
  { p: "Quantas Copas do Mundo a Itália venceu?", ops: ["4", "3", "5", "2"], r: 0, d: 3 },
  { p: "Como a Itália venceu a final da Copa de 2006?", ops: ["Nos pênaltis contra a França", "Por 2 a 0 contra a Alemanha", "Na prorrogação contra o Brasil", "Por 3 a 2 contra a Holanda"], r: 0, d: 3 },
  { p: "Qual empresa fabrica a Vespa?", ops: ["Piaggio", "Ducati", "Aprilia", "Lancia"], r: 0, d: 3 },
  { p: "Como se chama a máfia siciliana?", ops: ["Cosa Nostra", "Camorra", "'Ndrangheta", "Sacra Corona"], r: 0, d: 3 },
  { p: "A Pietà de Michelangelo fica em...", ops: ["São Pedro (Vaticano)", "Uffizi", "Duomo de Milão", "Santa Croce"], r: 0, d: 3 },
  { p: "A Ponte Vecchio de Florença é ocupada por lojas de...", ops: ["joias", "couro", "vinho", "livros"], r: 0, d: 3 },
  { p: "O Palio di Siena é uma tradicional corrida de...", ops: ["cavalos", "gôndolas", "bigas", "vespas"], r: 0, d: 3 },
  { p: "Ferragosto, o feriadão italiano, cai em...", ops: ["15 de agosto", "1º de agosto", "15 de julho", "31 de agosto"], r: 0, d: 3 },
  { p: "Quem traz doces às crianças italianas na Epifania?", ops: ["A Befana (bruxa boa)", "São Nicolau", "O Menino Jesus", "A Fada Turquesa"], r: 0, d: 3 },
  { p: "Tradicionalmente, as gôndolas de Veneza são de qual cor?", ops: ["Pretas", "Vermelhas", "Azuis", "Douradas"], r: 0, d: 3 },
  { p: "O tomate San Marzano, rei do molho, cresce aos pés de qual vulcão?", ops: ["Vesúvio", "Etna", "Stromboli", "Vulcano"], r: 0, d: 3 },
  { p: "A focaccia é orgulho de qual região?", ops: ["Ligúria", "Puglia", "Toscana", "Sicília"], r: 0, d: 3 },
  { p: "O prosecco vem principalmente de qual região?", ops: ["Vêneto", "Toscana", "Piemonte", "Umbria"], r: 0, d: 3 },
  { p: "O parmigiano reggiano é produzido em qual região?", ops: ["Emília-Romanha", "Lombardia", "Vêneto", "Trentino"], r: 0, d: 3 },
  { p: "A verdadeira mozzarella di bufala vem de qual região?", ops: ["Campânia", "Puglia", "Sicília", "Calábria"], r: 0, d: 3 },
  { p: "O 'derby della Capitale' é o clássico entre...", ops: ["Roma e Lazio", "Milan e Inter", "Juventus e Torino", "Napoli e Roma"], r: 0, d: 3 },
  { p: "Qual trio de massas é considerado o 'santíssima trindade' romano?", ops: ["Carbonara, amatriciana e cacio e pepe", "Pesto, bolonhesa e alfredo", "Lasanha, nhoque e ravióli", "Puttanesca, arrabiata e norma"], r: 0, d: 3 },
  { p: "A amatriciana leva tomate, pecorino e...", ops: ["guanciale", "frango", "berinjela", "atum"], r: 0, d: 3 }
];
